volumes:
  redis_data:
services:
  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    # persistent storage
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
