#!/bin/bash
PATH=./node_modules/.bin:$PATH

function help {
    echo "$0 <task> <args>"
    echo "Tasks:"
    compgen -A function | cat -n
}

function migrate {
    ./manage.py migrate
}

function server {
    ./manage.py runserver
}

function tests {
    tox -e py36-django31 $@
}

TIMEFORMAT="Task completed in %3lR"
time ${@:-server}
