# Generated by Django 5.2 on 2025-05-10 19:29

import django.db.models.deletion
import webquills.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commoncontent', '0003_add_image_set_attachment_set'),
        ('sites', '0002_alter_blockreason_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanBlogArticleLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_layout', to='commoncontent.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Clean Blog Article Layout',
                'verbose_name_plural': 'Clean Blog Article Layouts',
            },
            bases=(webquills.models.BaseLayout, models.Model),
        ),
        migrations.CreateModel(
            name='CleanBlogArticleSeriesLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_layout', to='commoncontent.articleseries', verbose_name='Article Series')),
            ],
            options={
                'verbose_name': 'Clean Blog Article Series Layout',
                'verbose_name_plural': 'Clean Blog Article Series Layouts',
            },
            bases=(webquills.models.BaseLayout, models.Model),
        ),
        migrations.CreateModel(
            name='CleanBlogHomePageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_layout', to='commoncontent.homepage', verbose_name='Home Page')),
            ],
            options={
                'verbose_name': 'Clean Blog Home Page Layout',
                'verbose_name_plural': 'Clean Blog Home Page Layouts',
            },
            bases=(webquills.models.BaseLayout, models.Model),
        ),
        migrations.CreateModel(
            name='CleanBlogPageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_layout', to='commoncontent.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Clean Blog Page Layout',
                'verbose_name_plural': 'Clean Blog Page Layouts',
            },
            bases=(webquills.models.BaseLayout, models.Model),
        ),
        migrations.CreateModel(
            name='CleanBlogSectionLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_layout', to='commoncontent.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Clean Blog Section Layout',
                'verbose_name_plural': 'Clean Blog Section Layouts',
            },
            bases=(webquills.models.BaseLayout, models.Model),
        ),
        migrations.CreateModel(
            name='CleanBlogSiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleanblog_theme', to='sites.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Clean Blog Site Theme',
                'verbose_name_plural': 'Clean Blog Site Themes',
            },
        ),
    ]
