# Generated by Django 4.2.11 on 2024-03-20 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wqcontent", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-date_published"],
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
    ]
