# Generated by Django 5.2 on 2025-04-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(help_text='Subdomain for the site', max_length=64, unique=True, verbose_name='subdomain')),
                ('normalized_subdomain', models.SlugField(help_text='Normalized subdomain for the site', max_length=64, unique=True, verbose_name='normalized subdomain')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('archive_date', models.DateTimeField(blank=True, null=True)),
                ('archived_canonical_name', models.CharField(blank=True, max_length=255)),
                ('block_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.blockreason')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='site', to='auth.group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_domain', models.CharField(max_length=255, unique=True)),
                ('normalized_domain', models.CharField(max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_canonical', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='sites.site')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('site',), name='unique_primary_domain'), models.UniqueConstraint(condition=models.Q(('is_canonical', True)), fields=('site',), name='unique_canonical_domain')],
            },
        ),
    ]
