# Generated by Django 5.2 on 2025-05-10 19:29

import webquills.themes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockreason',
            options={'ordering': ['name'], 'verbose_name': 'block reason', 'verbose_name_plural': 'block reasons'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'ordering': ['site', 'normalized_domain'], 'verbose_name': 'domain', 'verbose_name_plural': 'domains'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['subdomain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
        migrations.AddField(
            model_name='site',
            name='theme_app',
            field=models.CharField(choices=webquills.themes.get_theme_choices, default='cleanblog', help_text='Choose a theme for the site', max_length=255),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['site'], name='sites_domai_site_id_0b9e64_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['normalized_domain'], name='sites_domai_normali_0ac41f_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['is_primary'], name='sites_domai_is_prim_e5a1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='domain',
            index=models.Index(fields=['is_canonical'], name='sites_domai_is_cano_f46890_idx'),
        ),
    ]
