# Generated by Django 3.2 on 2021-06-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
        ('webquills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Default author for any page without an explicit author', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.author', verbose_name='author'),
        ),
    ]
