# Generated by Django 3.2 on 2021-06-07 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import tinymce.models
import webquills.core.images


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byline', models.CharField(blank=True, help_text="As in a newspaper byline, a name to attribute authorship of an article, e.g. 'Edward R. Murrow' (omit the word 'by').", max_length=255, verbose_name='byline')),
                ('about', tinymce.models.HTMLField(blank=True, help_text="A paragraph or two about the author. May include a headshot, links to the author's website, recent publications, etc. Typically displayed in article footer or sidebar. ", verbose_name='about')),
                ('copyright_holder', models.CharField(blank=True, help_text="Name to use in copyright notice as owner, e.g. 'Galactic Media LLC'. If the material is not subject to copyright, or you don't want a default copyright notice printed, leave blank and explain in the copyright notice field. ", max_length=255, verbose_name='copyright holder')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='CopyrightLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short name for use in the admin', max_length=50, verbose_name='name')),
                ('notice', tinymce.models.HTMLField(default='All rights reserved.', help_text='Text to follow the copyright notice indicating any license', verbose_name='copyright license notice')),
                ('url', models.CharField(blank=True, help_text='Link to the full copyright license. Leave blank if the notice contains a link to the license. ', max_length=255, null=True, verbose_name='copyright license URL')),
            ],
            options={
                'verbose_name': 'copyright license',
                'verbose_name_plural': 'copyright licenses',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', tinymce.models.HTMLField(blank=True, help_text='Additional credits (typically displayed in footer or sidebar)', verbose_name='credits')),
                ('custom_byline', models.CharField(blank=True, help_text="As in a newspaper byline, a name to attribute authorship of an article, e.g. 'Edward R. Murrow' (omit the word 'by').", max_length=255, verbose_name='byline')),
                ('custom_about', tinymce.models.HTMLField(blank=True, help_text="A paragraph or two about the author. May include a headshot, links to the author's website, recent publications, etc. Typically displayed in article footer or sidebar. ", verbose_name='about')),
                ('custom_copyright_holder', models.CharField(blank=True, help_text="Name to use in copyright notice as owner, e.g. 'Galactic Media LLC'. If the material is not subject to copyright, or you don't want a default copyright notice printed, leave blank and explain in the copyright notice field. ", max_length=255, verbose_name='copyright holder')),
                ('custom_copyright_notice', tinymce.models.HTMLField(blank=True, help_text='A custom copyright notice to replace the default. ', verbose_name='copyright notice')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('file', models.ImageField(height_field='height', upload_to=webquills.core.images.img_upload_to, verbose_name='file', width_field='width')),
                ('width', models.IntegerField(editable=False, verbose_name='width')),
                ('height', models.IntegerField(editable=False, verbose_name='height')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='alt text')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('copyright_date', models.DateField(blank=True, null=True, verbose_name='copyright year')),
                ('focal_point_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(editable=False, null=True)),
                ('thumbs', models.JSONField(blank=True, default=list, help_text='Resized versions of the image that have been generated', verbose_name='thumbnails')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.author', verbose_name='author')),
                ('custom_copyright_license', models.ForeignKey(blank=True, help_text='Select a standard license to apply, or leave blank to use the site default. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.copyrightlicense')),
                ('site', models.ForeignKey(help_text='Note: images are associated with a site, but are physically shared among all sites. ', on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', tinymce.models.HTMLField(blank=True, help_text='Additional credits (typically displayed in footer or sidebar)', verbose_name='credits')),
                ('custom_byline', models.CharField(blank=True, help_text="As in a newspaper byline, a name to attribute authorship of an article, e.g. 'Edward R. Murrow' (omit the word 'by').", max_length=255, verbose_name='byline')),
                ('custom_about', tinymce.models.HTMLField(blank=True, help_text="A paragraph or two about the author. May include a headshot, links to the author's website, recent publications, etc. Typically displayed in article footer or sidebar. ", verbose_name='about')),
                ('custom_copyright_holder', models.CharField(blank=True, help_text="Name to use in copyright notice as owner, e.g. 'Galactic Media LLC'. If the material is not subject to copyright, or you don't want a default copyright notice printed, leave blank and explain in the copyright notice field. ", max_length=255, verbose_name='copyright holder')),
                ('custom_copyright_notice', tinymce.models.HTMLField(blank=True, help_text='A custom copyright notice to replace the default. ', verbose_name='copyright notice')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='page title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('headline', models.CharField(max_length=255, verbose_name='headline')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(choices=[('withheld', 'Draft (withheld)'), ('usable', 'Publish (usable)'), ('cancelled', 'Unpublish (cancelled)')], db_index=True, default='withheld', help_text='Controls visibility (must be Published/Usable to be visible).', max_length=50, verbose_name='status')),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Publication date for copyright purposes. Also controls visibility (must be published in the past to be visible).', verbose_name='published')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('expired', models.DateTimeField(blank=True, db_index=True, help_text='Time after which the content is no longer valid. Controls visibility (expired, if set, must be in the future to be visible).', null=True, verbose_name='expired')),
                ('lead', tinymce.models.HTMLField(blank=True, help_text='Paragraph leading reader to the action.', verbose_name='lead paragraph')),
                ('action_label', models.CharField(default='Learn more', help_text='The label on the action button or link', max_length=50, verbose_name='action label')),
                ('target_url', models.URLField(blank=True, help_text='CTA will either link/submit to a landing page on site, or to an external target URL. Choose only one.', null=True, verbose_name='target URL')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.author', verbose_name='author')),
                ('custom_copyright_license', models.ForeignKey(blank=True, help_text='Select a standard license to apply, or leave blank to use the site default. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.copyrightlicense')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.image', verbose_name='featured image')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.image', verbose_name='picture')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homepages', to='sites.site', verbose_name='site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'home page',
                'verbose_name_plural': 'home pages',
                'ordering': ['-published'],
                'get_latest_by': 'published',
            },
        ),
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', tinymce.models.HTMLField(blank=True, help_text='Additional credits (typically displayed in footer or sidebar)', verbose_name='credits')),
                ('custom_byline', models.CharField(blank=True, help_text="As in a newspaper byline, a name to attribute authorship of an article, e.g. 'Edward R. Murrow' (omit the word 'by').", max_length=255, verbose_name='byline')),
                ('custom_about', tinymce.models.HTMLField(blank=True, help_text="A paragraph or two about the author. May include a headshot, links to the author's website, recent publications, etc. Typically displayed in article footer or sidebar. ", verbose_name='about')),
                ('custom_copyright_holder', models.CharField(blank=True, help_text="Name to use in copyright notice as owner, e.g. 'Galactic Media LLC'. If the material is not subject to copyright, or you don't want a default copyright notice printed, leave blank and explain in the copyright notice field. ", max_length=255, verbose_name='copyright holder')),
                ('custom_copyright_notice', tinymce.models.HTMLField(blank=True, help_text='A custom copyright notice to replace the default. ', verbose_name='copyright notice')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='page title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('headline', models.CharField(max_length=255, verbose_name='headline')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(choices=[('withheld', 'Draft (withheld)'), ('usable', 'Publish (usable)'), ('cancelled', 'Unpublish (cancelled)')], db_index=True, default='withheld', help_text='Controls visibility (must be Published/Usable to be visible).', max_length=50, verbose_name='status')),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Publication date for copyright purposes. Also controls visibility (must be published in the past to be visible).', verbose_name='published')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('expired', models.DateTimeField(blank=True, db_index=True, help_text='Time after which the content is no longer valid. Controls visibility (expired, if set, must be in the future to be visible).', null=True, verbose_name='expired')),
                ('intro', tinymce.models.HTMLField(blank=True, verbose_name='intro')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.author', verbose_name='author')),
                ('custom_copyright_license', models.ForeignKey(blank=True, help_text='Select a standard license to apply, or leave blank to use the site default. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.copyrightlicense')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.image', verbose_name='featured image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorypages', to='sites.site', verbose_name='site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'category page',
                'verbose_name_plural': 'category pages',
                'ordering': ['-published'],
                'get_latest_by': 'published',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='copyright_license',
            field=models.ForeignKey(blank=True, help_text="Select a standard license to apply, or leave blank for 'All rights reserved'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.copyrightlicense'),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', tinymce.models.HTMLField(blank=True, help_text='Additional credits (typically displayed in footer or sidebar)', verbose_name='credits')),
                ('custom_byline', models.CharField(blank=True, help_text="As in a newspaper byline, a name to attribute authorship of an article, e.g. 'Edward R. Murrow' (omit the word 'by').", max_length=255, verbose_name='byline')),
                ('custom_about', tinymce.models.HTMLField(blank=True, help_text="A paragraph or two about the author. May include a headshot, links to the author's website, recent publications, etc. Typically displayed in article footer or sidebar. ", verbose_name='about')),
                ('custom_copyright_holder', models.CharField(blank=True, help_text="Name to use in copyright notice as owner, e.g. 'Galactic Media LLC'. If the material is not subject to copyright, or you don't want a default copyright notice printed, leave blank and explain in the copyright notice field. ", max_length=255, verbose_name='copyright holder')),
                ('custom_copyright_notice', tinymce.models.HTMLField(blank=True, help_text='A custom copyright notice to replace the default. ', verbose_name='copyright notice')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='page title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('headline', models.CharField(max_length=255, verbose_name='headline')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('status', models.CharField(choices=[('withheld', 'Draft (withheld)'), ('usable', 'Publish (usable)'), ('cancelled', 'Unpublish (cancelled)')], db_index=True, default='withheld', help_text='Controls visibility (must be Published/Usable to be visible).', max_length=50, verbose_name='status')),
                ('published', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Publication date for copyright purposes. Also controls visibility (must be published in the past to be visible).', verbose_name='published')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated')),
                ('expired', models.DateTimeField(blank=True, db_index=True, help_text='Time after which the content is no longer valid. Controls visibility (expired, if set, must be in the future to be visible).', null=True, verbose_name='expired')),
                ('body', tinymce.models.HTMLField(blank=True, help_text="Article text, excluding the headline (provided by 'title'). ", verbose_name='article body')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.author', verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webquills.categorypage', verbose_name='category')),
                ('custom_copyright_license', models.ForeignKey(blank=True, help_text='Select a standard license to apply, or leave blank to use the site default. ', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webquills.copyrightlicense')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='webquills.image', verbose_name='featured image')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articlepages', to='sites.site', verbose_name='site')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'article page',
                'verbose_name_plural': 'article pages',
                'ordering': ['-published'],
                'get_latest_by': 'published',
            },
        ),
    ]
