# Generated by Django 3.2 on 2021-06-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webquills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteMeta',
        ),
    ]
