# Generated by Django 3.0.3 on 2020-02-23 19:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('webquills', '0002_auto_20200222_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='usage_terms',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Textual description (for humans) describing any restrictions or terms of use. ', null=True, verbose_name='usage terms'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='copyright_year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='copyright year'),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='credit',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='How attribution should appear on site. May include links to source. May be left blank if attribution is not required/desired. Example: Special guest post by Phil Colson, Agent of S.H.I.E.L.D. ', null=True, verbose_name='credit'),
        ),
        migrations.AlterField(
            model_name='footertext',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('heading_text', wagtail.core.blocks.CharBlock(classname='title', required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=False, choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]))])), ('paragraph_block', wagtail.core.blocks.RichTextBlock()), ('image_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock()), ('attribution', wagtail.core.blocks.CharBlock(blank=True, label='e.g. Mary Berry', required=False))])), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks', icon='fa-s15', template='webquills/blocks/embed_block.html'))], blank=True, verbose_name='Page body'),
        ),
    ]
