# Generated by Django 3.2 on 2021-06-07 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wqsites', '0001_initial'),
        ('webquills', '0002_delete_sitemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articlepages', to='wqsites.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='categorypage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorypages', to='wqsites.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homepages', to='wqsites.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='image',
            name='site',
            field=models.ForeignKey(help_text='Note: images are associated with a site, but are physically shared among all sites. ', on_delete=django.db.models.deletion.PROTECT, to='wqsites.site', verbose_name='site'),
        ),
    ]
