# Generated by Django 3.1.7 on 2021-04-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquills', '0002_sitemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='orig_published_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If published before being added to this site, set the original publish date here.', null=True, verbose_name='original publish date'),
        ),
    ]
