# Generated by Django 3.1.7 on 2021-04-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquills', '0004_auto_20210403_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date of the most recent significant editorial update, if any.', null=True, verbose_name='updated date'),
        ),
    ]
