# Generated by Django 3.1.7 on 2021-04-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webquills', '0007_auto_20210405_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='extra',
        ),
        migrations.AddField(
            model_name='calltoaction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
    ]
