# Generated by Django 3.1.7 on 2021-04-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webquills', '0008_auto_20210405_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='landing_page',
            field=models.ForeignKey(blank=True, help_text='CTA will either link/submit to a landing page on site, or to an external target URL. Choose only one.', null=True, on_delete=django.db.models.deletion.PROTECT, to='wagtailcore.page', verbose_name='landing page'),
        ),
        migrations.AlterField(
            model_name='calltoaction',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='picture'),
        ),
    ]
