# Generated by Django 3.2 on 2021-06-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('text', models.CharField(max_length=50, verbose_name='text')),
                ('icon', models.CharField(default='link-45deg', help_text='<a href=https://icons.getbootstrap.com/#icons target=iconlist>icon list</a>', max_length=50, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
            options={
                'verbose_name': 'link list',
                'verbose_name_plural': 'link lists',
            },
        ),
    ]
