# Generated by Django 3.2.7 on 2021-10-10 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linkmgr', '0003_alter_link_icon'),
        ('sites', '0002_site_author'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the admin, not visible to the public', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('headline', models.TextField(blank=True, default='', help_text='A title for the list, visible on the public web site', max_length=255, verbose_name='headline')),
            ],
            options={
                'verbose_name': 'modulelist',
                'verbose_name_plural': 'modulelists',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the admin, not visible to public', max_length=255, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('base_stylesheet', models.CharField(choices=[('https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css', 'Bootstrap: Stock Bootstrap 4'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/cerulean/bootstrap.min.css', 'Cerulean: A calm blue sky'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/cosmo/bootstrap.min.css', 'Cosmo: An ode to Metro'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/cyborg/bootstrap.min.css', 'Cyborg: Jet black and electric blue'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/darkly/bootstrap.min.css', 'Darkly: Flatly in night mode'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/flatly/bootstrap.min.css', 'Flatly: Flat and modern'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/journal/bootstrap.min.css', 'Journal: Crisp like a new sheet of paper'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/litera/bootstrap.min.css', 'Litera: The medium is the message'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/lumen/bootstrap.min.css', 'Lumen: Light and shadow'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/lux/bootstrap.min.css', 'Lux: A touch of class'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/materia/bootstrap.min.css', 'Materia: Material is the metaphor'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/minty/bootstrap.min.css', 'Minty: A fresh feel'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/pulse/bootstrap.min.css', 'Pulse: A trace of purple'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/sandstone/bootstrap.min.css', 'Sandstone: A touch of warmth'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/simplex/bootstrap.min.css', 'Simplex: Mini and minimalist'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/sketchy/bootstrap.min.css', 'Sketchy: A hand-drawn look for mockups and mirth'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/slate/bootstrap.min.css', 'Slate: Shades of gunmetal gray'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/solar/bootstrap.min.css', 'Solar: A spin on Solarized'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/spacelab/bootstrap.min.css', 'Spacelab: Silvery and sleek'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/superhero/bootstrap.min.css', 'Superhero: The brave and the blue'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/united/bootstrap.min.css', 'United: Ubuntu orange and unique font'), ('https://cdn.jsdelivr.net/npm/bootswatch@4.6.0/dist/yeti/bootstrap.min.css', 'Yeti: A friendly foundation')], default='https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css', max_length=255, verbose_name='base stylesheet')),
                ('custom_stylesheet', models.FilePathField(blank=True, default='', match='.*\\.css$', max_length=255, path='/Users/vince/Devel/webquills/var/static', recursive=True, verbose_name='custom stylesheet')),
                ('custom_footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bs4theme.modulelist', verbose_name='custom footer')),
                ('custom_nav_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='linkmgr.linkcategory', verbose_name='navigation menu')),
                ('custom_sidebar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bs4theme.modulelist', verbose_name='custom sidebar')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='ThemeModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
                ('module_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs4theme.modulelist', verbose_name='list')),
            ],
            options={
                'verbose_name': 'theme module',
                'verbose_name_plural': 'theme modules',
                'order_with_respect_to': 'module_list',
            },
        ),
    ]
